# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-07 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('webapp', '0004_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=500)),
                ('Roll_no', models.CharField(max_length=150)),
                ('Distnace', models.FloatField(default=0)),
                ('Velocity', models.FloatField(default=0)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
